join:
  jointitle: "&cBienvenue %player%"
  joinsubtitle: "&eBon jeu sur Volcania !"
  staffjoinmessage: "&bLe membre du staff &4%player% &bviens de rejoindre le serveur !"
  staffquitmessage: "&bLe membre du staff &4%player% &bviens de quitter le serveur !"
  join_enter_fade: 15
  join_time: 40
  join_quit_fade: 15

compass:
  title: '&cTéléporteur - Volcania'
  already_have_error: '&c[VolcaCompass] &rVous avez déjà un Compass dans votre inventaire !'
  volcania:
    server_name: volcania
    item_icon: FIRE_CHARGE
    item_name: '&cPvP Faction - Volcania'
  minijeux:
    server_name: jump
    item_icon: SLIME_BLOCK
    item_name: '&cLobby - MiniJeux'
  minage:
    server_name: minage
    item_icon: DIAMOND_PICKAXE
    item_name: '&cServeur Minage - Minage'
  lobby:
    server_name: lobby
    item_icon: BLACK_BED
    item_name: '&cLobby - Lobby Général'

shop:
  inv_name: "&cShop - Volcania"
  item_amount: 2
  not_enouth_money_message: "&4&l[Volcania] &r&eDésolé &l&c%player%, &r&eVous n'avez pas assez d'argent sur votre compte"

  item1: "OAK_LOG"
  item1_price: 10
  item1_slot: 0
  item1_name: "&cBuche en Chene"

  item2: "BIRCH_FENCE"
  item2_price: 100
  item2_slot: 3
  item2_name: "&eBarrière en bouleau"
